######################################################################
# Automatically generated by qmake (3.0) Thu Nov 17 16:16:40 2016
######################################################################

TEMPLATE = app
TARGET = Slideshow
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
